### ISSUE TITLE
CassandraInterpreterTest fails with  java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by pravin-dsilva** [OpenPOWER-BigData/HDP2.5-zeppelin#1]
Project: Zeppelin: Apache Cassandra interpreter

Command used:  mvn test -fn     -Dhadoop.version=2.7.3.2.5.0.0-1245  -Dspark.version=1.6.2.2.5.0.0-1245  -Drat.skip

There are 2 errors seen: 
```
CassandraInterpreterTest.org.apache.zeppelin.cassandra.CassandraInterpreterTest Â» ExceptionInInitializer
CassandraInterpreterTest.org.apache.zeppelin.cassandra.CassandraInterpreterTest Â» NoClassDefFound
```

**Stacktrace:**
```
org.apache.zeppelin.cassandra.CassandraInterpreterTest Time elapsed: 30.485 sec <<< ERROR!
java.lang.ExceptionInInitializerError: null
at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:233)
at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)
at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1424)
at com.datastax.driver.core.Cluster.init(Cluster.java:163)
at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:334)
at com.datastax.driver.core.Cluster.connect(Cluster.java:284)
at info.archinnov.achilles.embedded.AchillesInitializer.createKeyspaceIfNeeded(AchillesInitializer.java:184)
at info.archinnov.achilles.embedded.AchillesInitializer.initialize(AchillesInitializer.java:96)
at info.archinnov.achilles.embedded.AchillesInitializer.initializeFromParameters(AchillesInitializer.java:61)
at info.archinnov.achilles.embedded.CassandraEmbeddedServer.<init>(CassandraEmbeddedServer.java:76)
at info.archinnov.achilles.embedded.CassandraEmbeddedServerBuilder.buildNativeSessionOnly(CassandraEmbeddedServerBuilder.java:436)
at org.apache.zeppelin.cassandra.CassandraInterpreterTest.<clinit>(CassandraInterpreterTest.java:65)


org.apache.zeppelin.cassandra.CassandraInterpreterTest Time elapsed: 30.486 sec <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.zeppelin.cassandra.CassandraInterpreterTest
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by pravin-dsilva** [comment]
Upon further debugging of this issue, it appears that the Cassandra server  does not start  hence the `NoHostAvailableException` is thrown at `com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:233)`

The below error is seen on additional debug statements

```
Connection exception
 Errors = {localhost/0:0:0:0:0:0:0:1:9239=com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect}
```

**Comment by pravin-dsilva** [comment]
On debugging the dependent projects that Apache Cassandra interpreter uses, the dependency Achilles has a dependency on Cassandra 2.2.3. Cassandra 2.2.3 has a dependency on JNA version 4.0.0 which is not compatible with Power. 

The errors are resolved when the JNA version 4.2.0 is used as this version has support for ppc64le.

**Comment by kadamvandita** [comment]
On checking out the latest version of Zappline 0.7, I am still getting the above test case failures on s390x systems.
